variable "instance_count" {}
variable "instance_type" {}
variable "ebs_optimized" {}
variable "ec2_size" {}
variable "name" {}
variable "port" {}
variable "protocol" {}
variable "region" {}
variable "vpc_name" {}
variable "stickiness" {}
variable "public_subnet_b" {}
variable "public_subnet_a" {}
variable "private_b_cidr" {}
variable "private_a_cidr" {}